# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de6a092b4c6d79aaa5985ebfaf1807fee47a9ced0d4a6d2a811247be7d55d55395bdb63187902bf58656a04f5bdf396f3f8b5d436448d036e166b3bfc66a4f7

test:
  secret_key_base: bfdc029b72613472e8daa1e4a4ec59ef12858aa117f5403bfe60cd478864fa8d02db84e4e09efcb34f53ff7dbad94a8b414d3a72cfe92591673b6da474d5e854

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
